
import type { Post } from '../types';
import { authors } from './UsersMock';

export const quotesData: Post[] = [
  {
    id: 40,
    title: 'சிந்தனை',
    author: authors.gandhi,
    category: 'மேற்கோள்',
    content: 'நேற்றைய பொழுதும் நமதல்ல, நாளைய பொழுதும் நமதல்ல, இன்றைக்கு மட்டுமே நம்முடையது.',
    likes: 256,
    comments: [],
    createdAt: '2023-10-25T14:30:00Z',
  },
  {
    id: 41,
    title: 'கனவு',
    author: authors.kalam,
    category: 'மேற்கோள்',
    content: 'கனவு காணுங்கள்! ஆனால் கனவு என்பது நீ தூக்கத்தில் காண்பது அல்ல; உன்னைத் தூங்க விடாமல் பண்ணுவது எதுவோ அதுவே கனவு.',
    likes: 1250,
    comments: [],
    createdAt: '2023-11-20T09:00:00Z',
  },
  {
    id: 42,
    title: 'முயற்சி',
    author: authors.vivekananda,
    category: 'மேற்கோள்',
    content: 'முயற்சி தன்மெய் வருத்தக் கூலி தரும். கடவுளே கைவிட்டாலும், உன் முயற்சி உனக்கான பலனைத் தரும்.',
    likes: 890,
    comments: [],
    createdAt: '2023-11-21T10:15:00Z',
  },
  {
    id: 43,
    title: 'நேரம்',
    author: authors.buddha,
    category: 'மேற்கோள்',
    content: 'இழந்த பணத்தை சம்பாதித்து விடலாம். இழந்த புகழை மீட்டு விடலாம். ஆனால் இழந்த நேரத்தை ஒருபோதும் மீட்க முடியாது.',
    likes: 675,
    comments: [],
    createdAt: '2023-11-22T11:30:00Z',
  },
  {
    id: 44,
    title: 'கல்வி',
    author: authors.kamarajar,
    category: 'மேற்கோள்',
    content: 'கல்வி என்பது தகவல்களை சேகரிப்பது மட்டுமல்ல; அது சிந்திக்கக் கற்றுத்தருவது. ஒரு தேசத்தின் எதிர்காலம் வகுப்பறைகளில் தான் உருவாக்கப்படுகிறது.',
    likes: 920,
    comments: [],
    createdAt: '2023-11-23T14:00:00Z',
  },
  {
    id: 45,
    title: 'அன்பு',
    author: authors.motherTeresa,
    category: 'மேற்கோள்',
    content: 'அன்பு ஒன்றுதான் அனாதை. அதைத் தேடித்தான் எல்லோரும் அலைகிறார்கள். அன்பு செய்வோம், அகிலத்தை வெல்வோம்.',
    likes: 1050,
    comments: [],
    createdAt: '2023-11-24T16:45:00Z',
  },
  {
    id: 46,
    title: 'தோல்வி',
    author: authors.kalam,
    category: 'மேற்கோள்',
    content: 'தோல்வி என்பது வெற்றியின் முதல் படி. கீழே விழுவது தவறல்ல, விழுந்த இடத்திலேயே கிடப்பதுதான் தவறு.',
    likes: 780,
    comments: [],
    createdAt: '2023-11-25T08:20:00Z',
  },
  {
    id: 47,
    title: 'கோபம்',
    author: authors.buddha,
    category: 'மேற்கோள்',
    content: 'கோபம் என்பது அடுத்தவர் செய்யும் தவறுக்கு உனக்கு நீயே கொடுத்துக்கொள்ளும் தண்டனை.',
    likes: 560,
    comments: [],
    createdAt: '2023-11-26T13:10:00Z',
  },
  {
    id: 48,
    title: 'மகிழ்ச்சி',
    author: authors.kannadasan,
    category: 'மேற்கோள்',
    content: 'மகிழ்ச்சி என்பது வெளியில் இல்லை, அது உன் உள்ளத்தில் இருக்கிறது. கிடைப்பதை வைத்து நிறைவு காண்பதே உண்மையான மகிழ்ச்சி.',
    likes: 810,
    comments: [],
    createdAt: '2023-11-27T15:30:00Z',
  },
  {
    id: 49,
    title: 'நட்பு',
    author: authors.muVaradharasanar,
    category: 'மேற்கோள்',
    content: 'நல்ல நண்பன் ஒரு கண்ணாடி போன்றவன். நீ அழும்போது அவன் சிரிக்க மாட்டான். உண்மையான நட்பு காலத்தால் அழியாது.',
    likes: 945,
    comments: [],
    createdAt: '2023-11-28T09:40:00Z',
  }
];
