
import React, { useState } from 'react';
import { t, Language } from '../utils/translations';
import { SEO } from './SEO';
import { Icon } from './Icon';
import { Breadcrumbs, BreadcrumbItem } from './Breadcrumbs';

interface TamilKarkaViewProps {
  language: Language;
  onNavigate: (page: 'home') => void;
}

// ... (Data definitions remain the same) ...
const pureVowels = [
  { char: 'அ', en: 'a', example: 'அம்மா', exEn: 'Amma (Mother)' },
  { char: 'ஆ', en: 'aa', example: 'ஆடு', exEn: 'Aadu (Goat)' },
  { char: 'இ', en: 'i', example: 'இலை', exEn: 'Ilai (Leaf)' },
  { char: 'ஈ', en: 'ee', example: 'ஈ', exEn: 'Ee (Fly)' },
  { char: 'உ', en: 'u', example: 'உரல்', exEn: 'Ural (Mortar)' },
  { char: 'ஊ', en: 'uu', example: 'ஊசி', exEn: 'Oosi (Needle)' },
  { char: 'எ', en: 'e', example: 'எலி', exEn: 'Eli (Rat)' },
  { char: 'ஏ', en: 'ae', example: 'ஏணி', exEn: 'Yeni (Ladder)' },
  { char: 'ஐ', en: 'ai', example: 'ஐவர்', exEn: 'Aivar (Five People)' },
  { char: 'ஒ', en: 'o', example: 'ஒட்டகம்', exEn: 'Ottagam (Camel)' },
  { char: 'ஓ', en: 'oa', example: 'ஓடம்', exEn: 'Odam (Boat)' },
  { char: 'ஔ', en: 'au', example: 'ஔவை', exEn: 'Avvai (Poet)' },
];
const aayuthamData = { char: 'ஃ', en: 'ak', example: 'எஃகு', exEn: 'Ekku (Steel)' };
const consonants = [
  { char: 'க்', en: 'ik', example: 'சக்கரம்', exEn: 'Sakkaram (Wheel)' },
  { char: 'ங்', en: 'ing', example: 'சங்கு', exEn: 'Sangu (Conch)' },
  { char: 'ச்', en: 'ich', example: 'பச்சை', exEn: 'Pachai (Green)' },
  { char: 'ஞ்', en: 'inj', example: 'இஞ்சி', exEn: 'Inji (Ginger)' },
  { char: 'ட்', en: 'it', example: 'பட்டம்', exEn: 'Pattam (Kite)' },
  { char: 'ண்', en: 'in', example: 'கண்', exEn: 'Kan (Eye)' },
  { char: 'த்', en: 'ith', example: 'வாத்து', exEn: 'Vaaththu (Duck)' },
  { char: 'ந்', en: 'inth', example: 'பந்து', exEn: 'Panthu (Ball)' },
  { char: 'ப்', en: 'ip', example: 'கப்பல்', exEn: 'Kappal (Ship)' },
  { char: 'ம்', en: 'im', example: 'மரம்', exEn: 'Maram (Tree)' },
  { char: 'ய்', en: 'iy', example: 'நாய்', exEn: 'Naai (Dog)' },
  { char: 'ர்', en: 'ir', example: 'தேர்', exEn: 'Ther (Chariot)' },
  { char: 'ல்', en: 'il', example: 'பல்', exEn: 'Pal (Tooth)' },
  { char: 'வ்', en: 'iv', example: 'செவ்வந்தி', exEn: 'Sevvanthi (Flower)' },
  { char: 'ழ்', en: 'izh', example: 'யாழ்', exEn: 'Yaazh (Harp)' },
  { char: 'ள்', en: 'il', example: 'வாள்', exEn: 'Vaal (Sword)' },
  { char: 'ற்', en: 'itr', example: 'புற்று', exEn: 'Putru (Anthill)' },
  { char: 'ன்', en: 'in', example: 'மான்', exEn: 'Maan (Deer)' },
];
const uyirmeiKa = [
  { combo: 'க் + அ', result: 'க', en: 'Ka' }, { combo: 'க் + ஆ', result: 'கா', en: 'Kaa' }, { combo: 'க் + இ', result: 'கி', en: 'Ki' }, { combo: 'க் + ஈ', result: 'கீ', en: 'Kee' }, { combo: 'க் + உ', result: 'கு', en: 'Ku' }, { combo: 'க் + ஊ', result: 'கூ', en: 'Koo' }, { combo: 'க் + எ', result: 'கெ', en: 'Ke' }, { combo: 'க் + ஏ', result: 'கே', en: 'Kae' }, { combo: 'க் + ஐ', result: 'கை', en: 'Kai' }, { combo: 'க் + ஒ', result: 'கொ', en: 'Ko' }, { combo: 'க் + ஓ', result: 'கோ', en: 'Koa' }, { combo: 'க் + ஔ', result: 'கௌ', en: 'Kau' },
];
const numbers = [
  { num: 1, tamilChar: '௧', word: 'ஒன்று', en: 'Ondru' }, { num: 2, tamilChar: '௨', word: 'இரண்டு', en: 'Irandu' }, { num: 3, tamilChar: '௩', word: 'மூன்று', en: 'Moondru' }, { num: 4, tamilChar: '௪', word: 'நான்கு', en: 'Naangu' }, { num: 5, tamilChar: '௫', word: 'ஐந்து', en: 'Aindhu' }, { num: 6, tamilChar: '௬', word: 'ஆறு', en: 'Aaru' }, { num: 7, tamilChar: '௭', word: 'ஏழு', en: 'Yezhu' }, { num: 8, tamilChar: '௮', word: 'எட்டு', en: 'Ettu' }, { num: 9, tamilChar: '௯', word: 'ஒன்பது', en: 'Onbathu' }, { num: 10, tamilChar: '௰', word: 'பத்து', en: 'Pathu' },
];
const days = [
  { word: 'ஞாயிறு', en: 'Gnayiru', meaning: 'Sunday' }, { word: 'திங்கள்', en: 'Thingal', meaning: 'Monday' }, { word: 'செவ்வாய்', en: 'Sevvai', meaning: 'Tuesday' }, { word: 'புதன்', en: 'Budhan', meaning: 'Wednesday' }, { word: 'வியாழன்', en: 'Viyazhan', meaning: 'Thursday' }, { word: 'வெள்ளி', en: 'Velli', meaning: 'Friday' }, { word: 'சனி', en: 'Sani', meaning: 'Saturday' },
];
const months = [
  { word: 'சித்திரை', en: 'Chithirai', meaning: 'Mid Apr - Mid May' }, { word: 'வைகாசி', en: 'Vaikasi', meaning: 'Mid May - Mid Jun' }, { word: 'ஆனி', en: 'Aani', meaning: 'Mid Jun - Mid Jul' }, { word: 'ஆடி', en: 'Aadi', meaning: 'Mid Jul - Mid Aug' }, { word: 'ஆவணி', en: 'Aavani', meaning: 'Mid Aug - Mid Sep' }, { word: 'புரட்டாசி', en: 'Purattasi', meaning: 'Mid Sep - Mid Oct' }, { word: 'ஐப்பசி', en: 'Aippasi', meaning: 'Mid Oct - Mid Nov' }, { word: 'கார்த்திகை', en: 'Karthigai', meaning: 'Mid Nov - Mid Dec' }, { word: 'மார்கழி', en: 'Margazhi', meaning: 'Mid Dec - Mid Jan' }, { word: 'தை', en: 'Thai', meaning: 'Mid Jan - Mid Feb' }, { word: 'மாசி', en: 'Maasi', meaning: 'Mid Feb - Mid Mar' }, { word: 'பங்குனி', en: 'Panguni', meaning: 'Mid Mar - Mid Apr' },
];
const grammarTypes = [
  { title: 'எழுத்து', en: 'Ezhuthu', desc: 'எழுத்துக்களின் பிறப்பு, வகைகள் மற்றும் ஒலிப்பு முறைகளை விளக்குவது.', enDesc: 'Phonology: Deals with letters, their formation, and pronunciation.' }, { title: 'சொல்', en: 'Sol', desc: 'சொற்களின் வகைகள் (பெயர், வினை, இடை, உரி) மற்றும் அவற்றின் இலக்கணம்.', enDesc: 'Morphology: Deals with words, their classification, and formation.' }, { title: 'பொருள்', en: 'Porul', desc: 'வாழ்வியல் நெறிகள் (அகம், புறம்) மற்றும் கவிதைப் பொருளை விளக்குவது.', enDesc: 'Semantics: Deals with the subject matter of poetry (Love & War/Life).' }, { title: 'யாப்பு', en: 'Yaappu', desc: 'செய்யுள் இயற்றும் விதிகள், அசை, சீர், தளை, அடி, தொடை ஆகியவற்றை கூறுவது.', enDesc: 'Prosody: Rules of versification and poetry construction.' }, { title: 'அணி', en: 'Ani', desc: 'செய்யுளுக்கு அழகு சேர்க்கும் உவமை, உருவகம் போன்ற அணிகளை விளக்குவது.', enDesc: 'Rhetoric: Figures of speech and literary ornamentation.' }
];
const sentenceStructure = [
    { subject: 'நான்', subEn: 'I (Naan)', object: 'பழம்', objEn: 'Fruit (Pazham)', verb: 'சாப்பிட்டேன்', verbEn: 'Ate (Saappitten)', sentence: 'நான் பழம் சாப்பிட்டேன்', meaning: 'I ate a fruit' }, { subject: 'அவன்', subEn: 'He (Avan)', object: 'பள்ளிக்கு', objEn: 'To School (Pallikku)', verb: 'சென்றான்', verbEn: 'Went (Sendraan)', sentence: 'அவன் பள்ளிக்குச் சென்றான்', meaning: 'He went to school' }, { subject: 'அவள்', subEn: 'She (Aval)', object: 'பாடம்', objEn: 'Lesson (Paadam)', verb: 'படித்தாள்', verbEn: 'Studied (Padithaal)', sentence: 'அவள் பாடம் படித்தாள்', meaning: 'She studied the lesson' }
];
const commonPhrases = [
    { category: 'Greetings', items: [ { ta: 'வணக்கம்', en: 'Vanakkam', meaning: 'Hello / Greetings' }, { ta: 'நன்றி', en: 'Nandri', meaning: 'Thank you' }, { ta: 'காலை வணக்கம்', en: 'Kaalai Vanakkam', meaning: 'Good Morning' }, { ta: 'எப்படி இருக்கிறீர்கள்?', en: 'Eppadi irukkireergal?', meaning: 'How are you?' }, { ta: 'நான் நலம்', en: 'Naan nalam', meaning: 'I am fine' } ]}, { category: 'Essentials', items: [ { ta: 'ஆம்', en: 'Aam', meaning: 'Yes' }, { ta: 'இல்லை', en: 'Illai', meaning: 'No' }, { ta: 'மன்னிக்கவும்', en: 'Mannikkavum', meaning: 'Sorry / Excuse me' }, { ta: 'எனக்குத் தெரியாது', en: 'Enakku theriyadhu', meaning: 'I do not know' }, { ta: 'உதவி செய்யுங்கள்', en: 'Udhavi seiyungal', meaning: 'Please help' } ]}
];
const scriptGroups = [
    { name: 'Pa Family (Box Shape)', letters: ['ப', 'ம', 'ய', 'வ'] }, { name: 'Ta Family (Hook Shape)', letters: ['ட', 'ழ', 'ற'] }, { name: 'Ka Family', letters: ['க', 'ச', 'த', 'ந'] }, { name: 'La Family', letters: ['ல', 'வ'] }, { name: 'Na Family (Loop)', letters: ['ண', 'ன', 'ல'] }
];
const seasons = [
    { ta: 'இளவேனில்', en: 'Ilavenil', desc: 'Spring', months: 'சித்திரை - வைகாசி' }, { ta: 'முதுவேனில்', en: 'Muthuvenil', desc: 'Summer', months: 'ஆனி - ஆடி' }, { ta: 'கார்', en: 'Kaar', desc: 'Monsoon', months: 'ஆவணி - புரட்டாசி' }, { ta: 'குளிர்', en: 'Kulir', desc: 'Winter', months: 'ஐப்பசி - கார்த்திகை' }, { ta: 'முன்பனி', en: 'Munpani', desc: 'Early Dew', months: 'மார்கழி - தை' }, { ta: 'பின்பனி', en: 'Pinpani', desc: 'Late Dew', months: 'மாசி - பங்குனி' }
];
const directions = [ { ta: 'கிழக்கு', en: 'Kizhakku', desc: 'East' }, { ta: 'மேற்கு', en: 'Merku', desc: 'West' }, { ta: 'வடக்கு', en: 'Vadakku', desc: 'North' }, { ta: 'தெற்கு', en: 'Therku', desc: 'South' } ];
const tastes = [ { ta: 'இனிப்பு', en: 'Inippu', desc: 'Sweet', example: 'கரும்பு (Sugarcane)', color: 'bg-rose-100 text-rose-800' }, { ta: 'புளிப்பு', en: 'Pulippu', desc: 'Sour', example: 'எலுமிச்சை (Lemon)', color: 'bg-yellow-100 text-yellow-800' }, { ta: 'கசப்பு', en: 'Kasappu', desc: 'Bitter', example: 'பாகற்காய் (Bitter Gourd)', color: 'bg-green-100 text-green-800' }, { ta: 'உவர்ப்பு', en: 'Uvarppu', desc: 'Salty', example: 'உப்பு (Salt)', color: 'bg-stone-200 text-stone-800' }, { ta: 'காரப்பு', en: 'Kaarappu', desc: 'Spicy/Pungent', example: 'மிளகாய் (Chilli)', color: 'bg-red-100 text-red-800' }, { ta: 'துவர்ப்பு', en: 'Thuvarppu', desc: 'Astringent', example: 'பாக்கு (Betel Nut)', color: 'bg-purple-100 text-purple-800' } ];
const relations = [ { ta: 'அம்மா', en: 'Amma', desc: 'Mother' }, { ta: 'அப்பா', en: 'Appa', desc: 'Father' }, { ta: 'அண்ணன்', en: 'Annan', desc: 'Elder Brother' }, { ta: 'தம்பி', en: 'Thambi', desc: 'Younger Brother' }, { ta: 'அக்கா', en: 'Akka', desc: 'Elder Sister' }, { ta: 'தங்கை', en: 'Thangai', desc: 'Younger Sister' }, { ta: 'தாத்தா', en: 'Thaatha', desc: 'Grandfather' }, { ta: 'பாட்டி', en: 'Paatti', desc: 'Grandmother' }, { ta: 'மாமா', en: 'Maama', desc: 'Uncle (Maternal)' }, { ta: 'அத்தை', en: 'Athai', desc: 'Aunt (Paternal)' } ];
const colorsData = [ { ta: 'சிவப்பு', en: 'Sivappu', meaning: 'Red', class: 'bg-red-500' }, { ta: 'பச்சை', en: 'Pachai', meaning: 'Green', class: 'bg-green-500' }, { ta: 'நீலம்', en: 'Neelam', meaning: 'Blue', class: 'bg-blue-500' }, { ta: 'மஞ்சள்', en: 'Manjal', meaning: 'Yellow', class: 'bg-yellow-400' }, { ta: 'வெள்ளை', en: 'Vellai', meaning: 'White', class: 'bg-white border border-stone-200' }, { ta: 'கருப்பு', en: 'Karuppu', meaning: 'Black', class: 'bg-black' }, { ta: 'ஊதா', en: 'Oodha', meaning: 'Purple', class: 'bg-purple-500' }, { ta: 'செம்மஞ்சள்', en: 'Semmanjal', meaning: 'Orange', class: 'bg-orange-500' } ];
const animalsData = [ { ta: 'சிங்கம்', en: 'Singam', meaning: 'Lion' }, { ta: 'புலி', en: 'Puli', meaning: 'Tiger' }, { ta: 'யானை', en: 'Yaanai', meaning: 'Elephant' }, { ta: 'பசு', en: 'Pasu', meaning: 'Cow' }, { ta: 'குரங்கு', en: 'Kurangu', meaning: 'Monkey' }, { ta: 'மான்', en: 'Maan', meaning: 'Deer' }, { ta: 'நாய்', en: 'Naai', meaning: 'Dog' }, { ta: 'பூனை', en: 'Poonai', meaning: 'Cat' } ];
const birdsData = [ { ta: 'மயில்', en: 'Mayil', meaning: 'Peacock' }, { ta: 'கிளி', en: 'Kili', meaning: 'Parrot' }, { ta: 'காகம்', en: 'Kaagam', meaning: 'Crow' }, { ta: 'குயில்', en: 'Kuyil', meaning: 'Cuckoo' }, { ta: 'கழுகு', en: 'Kazhugu', meaning: 'Eagle' }, { ta: 'புறா', en: 'Puraa', meaning: 'Pigeon' }, { ta: 'வாத்து', en: 'Vaaththu', meaning: 'Duck' }, { ta: 'கோழி', en: 'Kozhi', meaning: 'Hen' } ];
const bodyPartsData = [ { ta: 'தலை', en: 'Thalai', meaning: 'Head' }, { ta: 'கண்', en: 'Kan', meaning: 'Eye' }, { ta: 'காது', en: 'Kaadhu', meaning: 'Ear' }, { ta: 'மூக்கு', en: 'Mookku', meaning: 'Nose' }, { ta: 'வாய்', en: 'Vaai', meaning: 'Mouth' }, { ta: 'கை', en: 'Kai', meaning: 'Hand' }, { ta: 'கால்', en: 'Kaal', meaning: 'Leg' }, { ta: 'பல்', en: 'Pal', meaning: 'Tooth' } ];
const vegetablesData = [ { ta: 'கத்திரிக்காய்', en: 'Kathirikkai', meaning: 'Brinjal' }, { ta: 'வெண்டைக்காய்', en: 'Vendaikkai', meaning: 'Okra' }, { ta: 'தக்காளி', en: 'Thakkali', meaning: 'Tomato' }, { ta: 'உருளைக்கிழங்கு', en: 'Urulaikizhangu', meaning: 'Potato' }, { ta: 'வெங்காயம்', en: 'Vengayam', meaning: 'Onion' }, { ta: 'முருங்கைக்காய்', en: 'Murungakkai', meaning: 'Drumstick' }, { ta: 'பூசணிக்காய்', en: 'Poosanikkai', meaning: 'Pumpkin' }, { ta: 'கேரட்', en: 'Carrot', meaning: 'Carrot' } ];
const fruitsData = [ { ta: 'மாம்பழம்', en: 'Maambazham', meaning: 'Mango' }, { ta: 'பலாப்பழம்', en: 'Palaapazham', meaning: 'Jackfruit' }, { ta: 'வாழைப்பழம்', en: 'Vaazhaipazham', meaning: 'Banana' }, { ta: 'எலுமிச்சை', en: 'Elumichai', meaning: 'Lemon' }, { ta: 'திராட்சை', en: 'Thiratchai', meaning: 'Grapes' }, { ta: 'கொய்யா', en: 'Koiya', meaning: 'Guava' }, { ta: 'மாதுளை', en: 'Maadhulai', meaning: 'Pomegranate' }, { ta: 'தர்பூசணி', en: 'Dharboosani', meaning: 'Watermelon' } ];
const flowersData = [ { ta: 'தாமரை', en: 'Thamarai', meaning: 'Lotus' }, { ta: 'மல்லிகை', en: 'Malligai', meaning: 'Jasmine' }, { ta: 'ரோஜா', en: 'Roja', meaning: 'Rose' }, { ta: 'செம்பருத்தி', en: 'Sembaruthi', meaning: 'Hibiscus' }, { ta: 'சூரியகாந்தி', en: 'Sooryakanthi', meaning: 'Sunflower' }, { ta: 'சாமந்தி', en: 'Saamanthi', meaning: 'Marigold' }, { ta: 'அல்லி', en: 'Alli', meaning: 'Lily' }, { ta: 'கனகாம்பரம்', en: 'Kanakambaram', meaning: 'Firecracker Flower' } ];
const shapesData = [ { ta: 'வட்டம்', en: 'Vattam', meaning: 'Circle', shapeClass: 'rounded-full' }, { ta: 'சதுரம்', en: 'Sadhuram', meaning: 'Square', shapeClass: 'rounded-none' }, { ta: 'செவ்வகம்', en: 'Sevvagam', meaning: 'Rectangle', shapeClass: 'w-full h-1/2 rounded-none' }, { ta: 'முக்கோணம்', en: 'Mukkonom', meaning: 'Triangle', shapeClass: 'triangle' } ];
const actionsData = [ { ta: 'நட', en: 'Nada', meaning: 'Walk' }, { ta: 'ஓடு', en: 'Odu', meaning: 'Run' }, { ta: 'சாப்பிடு', en: 'Saappidu', meaning: 'Eat' }, { ta: 'குடி', en: 'Kudi', meaning: 'Drink' }, { ta: 'தூங்கு', en: 'Thoongu', meaning: 'Sleep' }, { ta: 'படி', en: 'Padi', meaning: 'Read' }, { ta: 'எழுது', en: 'Ezhuthu', meaning: 'Write' }, { ta: 'விளையாடு', en: 'Vilaiyaadu', meaning: 'Play' } ];

type SectionId = 'vowels' | 'aayutham' | 'consonants' | 'uyirmei' | 'ilakkanam' | 'numbers' | 'days' | 'months' | 'sentences' | 'phrases' | 'script' | 'seasons' | 'directions' | 'tastes' | 'relations' | 'colors' | 'animals' | 'birds' | 'bodyParts' | 'vegetables' | 'fruits' | 'flowers' | 'shapes' | 'actions';

interface TopicConfig { id: SectionId; titleKey: string; count?: number; color: 'rose' | 'blue' | 'purple' | 'amber' | 'teal' | 'emerald' | 'indigo' | 'orange' | 'cyan' | 'lime' | 'fuchsia' | 'sky'; descKey?: string; }

const topics: TopicConfig[] = [
  { id: 'vowels', titleKey: 'vowels', count: 12, color: 'rose', descKey: 'vowelsDesc' }, { id: 'aayutham', titleKey: 'aayutham', count: 1, color: 'purple', descKey: 'aayuthamDesc' }, { id: 'consonants', titleKey: 'consonants', count: 18, color: 'blue', descKey: 'consonantsDesc' }, { id: 'uyirmei', titleKey: 'uyirmei', count: 216, color: 'amber', descKey: 'uyirmeiDesc' }, { id: 'colors', titleKey: 'colors', count: 8, color: 'fuchsia', descKey: 'colorsDesc' }, { id: 'shapes', titleKey: 'shapes', count: 4, color: 'indigo', descKey: 'shapesDesc' }, { id: 'vegetables', titleKey: 'vegetables', count: 8, color: 'emerald', descKey: 'vegetablesDesc' }, { id: 'fruits', titleKey: 'fruits', count: 8, color: 'orange', descKey: 'fruitsDesc' }, { id: 'flowers', titleKey: 'flowers', count: 8, color: 'rose', descKey: 'flowersDesc' }, { id: 'animals', titleKey: 'animals', count: 8, color: 'emerald', descKey: 'animalsDesc' }, { id: 'birds', titleKey: 'birds', count: 8, color: 'sky', descKey: 'birdsDesc' }, { id: 'bodyParts', titleKey: 'bodyParts', count: 8, color: 'orange', descKey: 'bodyPartsDesc' }, { id: 'actions', titleKey: 'actions', count: 8, color: 'cyan', descKey: 'actionsDesc' }, { id: 'script', titleKey: 'script', color: 'indigo', descKey: 'scriptDesc' }, { id: 'sentences', titleKey: 'sentences', color: 'orange', descKey: 'sentencesDesc' }, { id: 'phrases', titleKey: 'phrases', color: 'cyan', descKey: 'phrasesDesc' }, { id: 'ilakkanam', titleKey: 'ilakkanam', count: 5, color: 'teal', descKey: 'ilakkanamDesc' }, { id: 'numbers', titleKey: 'numbers', color: 'emerald', descKey: 'numbersDesc' }, { id: 'days', titleKey: 'days', count: 7, color: 'rose', descKey: 'daysDesc' }, { id: 'months', titleKey: 'months', count: 12, color: 'blue', descKey: 'monthsDesc' }, { id: 'seasons', titleKey: 'seasons', count: 6, color: 'lime', descKey: 'seasonsDesc' }, { id: 'directions', titleKey: 'directions', count: 4, color: 'sky', descKey: 'directionsDesc' }, { id: 'tastes', titleKey: 'tastes', count: 6, color: 'fuchsia', descKey: 'tastesDesc' }, { id: 'relations', titleKey: 'relations', color: 'amber', descKey: 'relationsDesc' },
];

export const TamilKarkaView: React.FC<TamilKarkaViewProps> = ({ language, onNavigate }) => {
  const [activeSection, setActiveSection] = useState<SectionId | null>(null);

  const getSectionTitle = (id: SectionId) => t(topics.find(t => t.id === id)!.titleKey as any, language);

  const breadcrumbs: BreadcrumbItem[] = [
      { label: t('home', language), onClick: () => onNavigate('home'), icon: 'home' as const },
      { label: t('learnTamil', language), onClick: () => setActiveSection(null), active: !activeSection, icon: 'school' as const }
  ];

  if (activeSection) {
      // Fix for Error: Explicitly typing the breadcrumbs array as BreadcrumbItem[] prevents specific inference issues.
      breadcrumbs.push({ label: getSectionTitle(activeSection), active: true });
  }

  const renderDashboard = () => (
    <div className="animate-fade-in">
       <div className="text-center mb-12">
        <h2 className="text-3xl md:text-5xl font-black font-tamil text-[#3e2b22] dark:text-white mb-4">{t('learnTamil', language)}</h2>
        <p className="text-[#8a7060] dark:text-stone-400 text-lg max-w-2xl mx-auto">தமிழ் எழுத்துக்கள் மற்றும் சொற்களை எளிமையாகக் கற்றுக்கொள்ளுங்கள்.</p>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8">
        {topics.map((topic) => {
           const colorClasses = { rose: 'bg-rose-50 text-rose-600 border-rose-100 hover:border-rose-300 dark:bg-rose-900/20 dark:text-rose-400 dark:border-rose-900/50', blue: 'bg-blue-50 text-blue-600 border-blue-100 hover:border-blue-300 dark:bg-blue-900/20 dark:text-blue-400 dark:border-blue-900/50', purple: 'bg-purple-50 text-purple-600 border-purple-100 hover:border-purple-300 dark:bg-purple-900/20 dark:text-purple-400 dark:border-purple-900/50', amber: 'bg-amber-50 text-amber-600 border-amber-100 hover:border-amber-300 dark:bg-amber-900/20 dark:text-amber-400 dark:border-amber-900/50', teal: 'bg-teal-50 text-teal-600 border-teal-100 hover:border-teal-300 dark:bg-teal-900/20 dark:text-teal-400 dark:border-teal-900/50', emerald: 'bg-emerald-50 text-emerald-600 border-emerald-100 hover:border-emerald-300 dark:bg-emerald-900/20 dark:text-emerald-400 dark:border-emerald-900/50', indigo: 'bg-indigo-50 text-indigo-600 border-indigo-100 hover:border-indigo-300 dark:bg-indigo-900/20 dark:text-indigo-400 dark:border-indigo-900/50', orange: 'bg-orange-50 text-orange-600 border-orange-100 hover:border-orange-300 dark:bg-orange-900/20 dark:text-orange-400 dark:border-orange-900/50', cyan: 'bg-cyan-50 text-cyan-600 border-cyan-100 hover:border-cyan-300 dark:bg-cyan-900/20 dark:text-cyan-400 dark:border-cyan-900/50', lime: 'bg-lime-50 text-lime-600 border-lime-100 hover:border-lime-300 dark:bg-lime-900/20 dark:text-lime-400 dark:border-lime-900/50', fuchsia: 'bg-fuchsia-50 text-fuchsia-600 border-fuchsia-100 hover:border-fuchsia-300 dark:bg-fuchsia-900/20 dark:text-fuchsia-400 dark:border-fuchsia-900/50', sky: 'bg-sky-50 text-sky-600 border-sky-100 hover:border-sky-300 dark:bg-sky-900/20 dark:text-sky-400 dark:border-sky-900/50' };
           const currentColors = colorClasses[topic.color];
           const bgClass = currentColors.split(' ')[0];
           return (
            <button key={topic.id} onClick={() => { setActiveSection(topic.id); window.scrollTo(0,0); }} className={`group relative text-left p-8 rounded-[2.5rem] border transition-all duration-300 hover:-translate-y-2 hover:shadow-xl shadow-lg shadow-stone-200/40 dark:shadow-none overflow-hidden ${currentColors}`}>
              <div className={`absolute -right-8 -bottom-8 w-32 h-32 rounded-full opacity-50 transition-transform duration-500 group-hover:scale-150 ${bgClass}`}></div>
              <div className="relative z-10">
                <div className="flex justify-between items-start mb-4"><div className="p-3 rounded-2xl bg-white dark:bg-[#1a1a1a] shadow-sm"><Icon name="school" /></div>{topic.count && <span className="font-sans font-bold text-2xl opacity-60">{topic.count}</span>}</div>
                <h3 className="text-2xl font-black font-tamil mb-2">{t(topic.titleKey as any, language)}</h3>
                <p className="text-sm font-medium opacity-80 line-clamp-2 leading-relaxed">{topic.descKey ? t(topic.descKey as any, language) : ''}</p>
                <div className="mt-6 flex items-center text-sm font-bold uppercase tracking-wider opacity-60 group-hover:opacity-100 transition-opacity"><span>படிக்கத் தொடங்க</span><Icon name="chevron-right" /></div>
              </div>
            </button>
           );
        })}
      </div>
    </div>
  );

  const renderSectionContent = () => {
    switch (activeSection) {
      case 'vowels': return <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4 sm:gap-6">{pureVowels.map((item, index) => <LearningCard key={index} mainText={item.char} subText={`/${item.en}/`} bottomText={item.example} bottomSubText={item.exEn} color="rose" />)}</div>;
      case 'aayutham': return <div className="flex justify-center h-[50vh] items-center"><div className="w-full max-w-[280px]"><LearningCard mainText={aayuthamData.char} subText={`/${aayuthamData.en}/`} bottomText={aayuthamData.example} bottomSubText={aayuthamData.exEn} color="purple" /></div></div>;
      case 'consonants': return <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4 sm:gap-6">{consonants.map((item, index) => <LearningCard key={index} mainText={item.char} subText={`/${item.en}/`} bottomText={item.example} bottomSubText={item.exEn} color="blue" />)}</div>;
      case 'uyirmei': return <><p className="text-center mb-8 text-[#8a7060] italic">({t('example', language)}: 'க' வரிசை)</p><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4 sm:gap-6">{uyirmeiKa.map((item, index) => <div key={index} className="group bg-white/80 dark:bg-[#1a1a1a] rounded-2xl p-4 border border-[#eaddcf] dark:border-neutral-800 shadow-lg hover:-translate-y-2 transition-all duration-300 flex flex-col items-center text-center"><div className="text-xs font-bold text-stone-400 mb-2">{item.combo}</div><div className="text-4xl font-black font-tamil text-amber-600 mb-2">{item.result}</div><div className="text-sm font-bold text-stone-500">{item.en}</div></div>)}</div></>;
      case 'ilakkanam': return <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">{grammarTypes.map((item, index) => <div key={index} className="group bg-white/80 dark:bg-[#1a1a1a] rounded-2xl p-8 border border-[#eaddcf] dark:border-neutral-800 shadow-lg hover:-translate-y-2 transition-all duration-300 flex flex-col items-center text-center relative overflow-hidden min-h-[280px] justify-center"><div className="absolute -top-10 -right-10 w-32 h-32 bg-teal-50 dark:bg-teal-900/20 rounded-full transition-transform group-hover:scale-150"></div><div className="w-14 h-14 bg-teal-100 dark:bg-teal-900/40 text-teal-600 dark:text-teal-400 rounded-full flex items-center justify-center font-bold text-xl mb-6 relative z-10">{index + 1}</div><h4 className="text-3xl font-black font-tamil text-teal-700 dark:text-teal-500 mb-2 relative z-10">{item.title}</h4><span className="text-xs font-bold text-[#8a7060] uppercase tracking-wider mb-6 relative z-10">{item.en}</span><p className="font-tamil text-lg font-medium text-[#5c4235] dark:text-stone-300 leading-snug mb-2 relative z-10">{item.desc}</p><p className="text-xs text-stone-400 dark:text-stone-500 leading-snug relative z-10">{item.enDesc}</p></div>)}</div>;
      case 'numbers': return <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-4 sm:gap-6">{numbers.map((item, index) => <div key={index} className="group bg-white/80 dark:bg-[#1a1a1a] rounded-2xl p-6 border border-[#eaddcf] dark:border-neutral-800 shadow-lg hover:-translate-y-2 transition-all duration-300 flex flex-col items-center text-center"><div className="text-5xl font-black text-[#eaddcf] dark:text-neutral-800 absolute top-2 right-4 select-none pointer-events-none">{item.num}</div><div className="text-4xl font-black font-tamil text-emerald-600 mb-3 relative z-10">{item.tamilChar}</div><div className="font-tamil font-bold text-lg text-[#3e2b22] dark:text-stone-200">{item.word}</div><div className="text-xs text-stone-400 font-bold uppercase">{item.en}</div></div>)}</div>;
      case 'days': return <div className="max-w-3xl mx-auto space-y-4">{days.map((day, idx) => <div key={idx} className="group flex items-center justify-between p-6 bg-white/80 dark:bg-[#1a1a1a] rounded-2xl border border-[#eaddcf] dark:border-neutral-800 shadow-sm hover:shadow-lg hover:-translate-y-1 transition-all duration-300"><span className="font-tamil font-black text-2xl text-[#3e2b22] dark:text-stone-100 group-hover:text-rose-600">{day.word}</span><div className="text-right"><span className="block text-sm font-bold text-[#5c4235] dark:text-stone-400">{day.meaning}</span><span className="block text-xs font-bold text-stone-300 uppercase tracking-wide">{day.en}</span></div></div>)}</div>;
      case 'months': return <div className="max-w-3xl mx-auto space-y-4">{months.map((month, idx) => <div key={idx} className="group flex items-center justify-between p-6 bg-white/80 dark:bg-[#1a1a1a] rounded-2xl border border-[#eaddcf] dark:border-neutral-800 shadow-sm hover:shadow-lg hover:-translate-y-1 transition-all duration-300"><div className="flex items-center gap-6"><span className="w-10 h-10 rounded-full bg-blue-50 dark:bg-blue-900/30 text-blue-600 flex items-center justify-center text-lg font-black group-hover:scale-110 transition-transform">{idx + 1}</span><span className="font-tamil font-black text-3xl text-[#3e2b22] dark:text-stone-100 group-hover:text-blue-600">{month.word}</span></div><div className="text-right"><span className="block text-sm font-bold text-[#5c4235] dark:text-stone-400">{month.meaning}</span><span className="block text-xs font-bold text-stone-300 uppercase tracking-wide">{month.en}</span></div></div>)}</div>;
      case 'seasons': return <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{seasons.map((season, idx) => <div key={idx} className="group bg-white/80 dark:bg-[#1a1a1a] p-8 rounded-3xl border border-[#eaddcf] dark:border-neutral-800 shadow-sm hover:shadow-lg hover:-translate-y-1 transition-all duration-300 flex flex-col items-center text-center relative overflow-hidden"><div className="absolute top-0 left-0 w-full h-2 bg-lime-500 opacity-50"></div><h4 className="font-tamil font-black text-3xl text-[#3e2b22] dark:text-stone-100 mb-1 group-hover:text-lime-600">{season.ta}</h4><span className="text-xs font-bold text-stone-400 uppercase tracking-widest mb-6">{season.en} - {season.desc}</span><div className="mt-auto bg-lime-50 dark:bg-lime-900/20 px-6 py-2 rounded-full border border-lime-100"><span className="font-tamil font-bold text-lime-800 dark:text-lime-300">{season.months}</span></div></div>)}</div>;
      case 'directions': return <div className="flex justify-center py-10"><div className="relative w-80 h-80 flex items-center justify-center"><div className="absolute w-4 h-4 bg-[#eaddcf] rounded-full z-10"></div><div className="absolute w-full h-0.5 bg-[#eaddcf]/50"></div><div className="absolute h-full w-0.5 bg-[#eaddcf]/50"></div><div className="absolute top-0 flex flex-col items-center -mt-8"><span className="font-tamil font-bold text-xl text-sky-600">வடக்கு</span><span className="text-xs font-bold text-stone-400 uppercase">North</span></div><div className="absolute bottom-0 flex flex-col items-center -mb-8"><span className="text-xs font-bold text-stone-400 uppercase">South</span><span className="font-tamil font-bold text-xl text-sky-600">தெற்கு</span></div><div className="absolute right-0 flex flex-col items-center -mr-16"><span className="font-tamil font-bold text-xl text-sky-600">கிழக்கு</span><span className="text-xs font-bold text-stone-400 uppercase">East</span></div><div className="absolute left-0 flex flex-col items-center -ml-16"><span className="font-tamil font-bold text-xl text-sky-600">மேற்கு</span><span className="text-xs font-bold text-stone-400 uppercase">West</span></div></div></div>;
      case 'tastes': return <div className="grid grid-cols-2 md:grid-cols-3 gap-6">{tastes.map((taste, idx) => <div key={idx} className="bg-white/80 dark:bg-[#1a1a1a] rounded-3xl p-6 border border-[#eaddcf] dark:border-neutral-800 shadow-sm hover:shadow-lg transition-all flex flex-col items-center text-center"><div className={`w-16 h-16 rounded-full flex items-center justify-center font-black text-2xl mb-4 ${taste.color}`}>{idx + 1}</div><h4 className="font-tamil font-black text-2xl text-[#3e2b22] dark:text-stone-100 mb-1">{taste.ta}</h4><span className="text-xs font-bold text-[#8a7060] uppercase tracking-widest mb-4">{taste.desc}</span><p className="text-sm font-medium text-[#5c4235] dark:text-stone-400 bg-[#fdf8f1] dark:bg-neutral-800 px-4 py-2 rounded-lg w-full">{taste.example}</p></div>)}</div>;
      case 'relations': return <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">{relations.map((rel, idx) => <div key={idx} className="bg-white/80 dark:bg-[#1a1a1a] p-6 rounded-2xl border border-[#eaddcf] dark:border-neutral-800 hover:border-amber-300 transition-colors text-center"><div className="w-12 h-12 bg-amber-50 dark:bg-amber-900/20 text-amber-600 rounded-full flex items-center justify-center mx-auto mb-3"><Icon name="like" /></div><h4 className="font-tamil font-bold text-xl text-[#3e2b22] dark:text-stone-100">{rel.ta}</h4><span className="text-xs font-bold text-stone-400 uppercase">{rel.en}</span><p className="text-xs text-stone-500 mt-2">{rel.desc}</p></div>)}</div>;
      case 'colors': return <div className="grid grid-cols-2 md:grid-cols-4 gap-6">{colorsData.map((color, idx) => <LearningCard key={idx} topElement={<div className={`w-24 h-24 rounded-full mb-4 shadow-inner ${color.class}`}></div>} mainText={color.ta} subText={color.en} color="fuchsia" />)}</div>;
      case 'animals': return <div className="grid grid-cols-2 md:grid-cols-4 gap-6">{animalsData.map((animal, idx) => <LearningCard key={idx} topElement={<div className="w-16 h-16 bg-emerald-50 dark:bg-emerald-900/20 text-emerald-600 rounded-2xl flex items-center justify-center mb-2 text-2xl font-black">{animal.ta.charAt(0)}</div>} mainText={animal.ta} subText="" bottomText={animal.meaning} bottomSubText={animal.en} color="emerald" />)}</div>;
      case 'birds': return <div className="grid grid-cols-2 md:grid-cols-4 gap-6">{birdsData.map((bird, idx) => <LearningCard key={idx} topElement={<div className="w-16 h-16 bg-sky-50 dark:bg-sky-900/20 text-sky-600 rounded-2xl flex items-center justify-center mb-2 text-2xl font-black">{bird.ta.charAt(0)}</div>} mainText={bird.ta} subText="" bottomText={bird.meaning} bottomSubText={bird.en} color="sky" />)}</div>;
      case 'bodyParts': return <div className="grid grid-cols-2 md:grid-cols-4 gap-6">{bodyPartsData.map((part, idx) => <LearningCard key={idx} topElement={<div className="w-16 h-16 bg-orange-50 dark:bg-orange-900/20 text-orange-600 rounded-2xl flex items-center justify-center mb-2 text-2xl font-black">{part.ta.charAt(0)}</div>} mainText={part.ta} subText="" bottomText={part.meaning} bottomSubText={part.en} color="orange" />)}</div>;
      case 'vegetables': return <div className="grid grid-cols-2 md:grid-cols-4 gap-6">{vegetablesData.map((veg, idx) => <LearningCard key={idx} topElement={<div className="w-16 h-16 bg-emerald-50 dark:bg-emerald-900/20 text-emerald-600 rounded-2xl flex items-center justify-center mb-2 text-2xl font-black">{veg.ta.charAt(0)}</div>} mainText={veg.ta} subText="" bottomText={veg.meaning} bottomSubText={veg.en} color="emerald" />)}</div>;
      case 'fruits': return <div className="grid grid-cols-2 md:grid-cols-4 gap-6">{fruitsData.map((fruit, idx) => <LearningCard key={idx} topElement={<div className="w-16 h-16 bg-orange-50 dark:bg-orange-900/20 text-orange-600 rounded-2xl flex items-center justify-center mb-2 text-2xl font-black">{fruit.ta.charAt(0)}</div>} mainText={fruit.ta} subText="" bottomText={fruit.meaning} bottomSubText={fruit.en} color="orange" />)}</div>;
      case 'flowers': return <div className="grid grid-cols-2 md:grid-cols-4 gap-6">{flowersData.map((flower, idx) => <LearningCard key={idx} topElement={<div className="w-16 h-16 bg-rose-50 dark:bg-rose-900/20 text-rose-600 rounded-2xl flex items-center justify-center mb-2 text-2xl font-black">{flower.ta.charAt(0)}</div>} mainText={flower.ta} subText="" bottomText={flower.meaning} bottomSubText={flower.en} color="rose" />)}</div>;
      case 'shapes': return <div className="grid grid-cols-2 md:grid-cols-4 gap-6">{shapesData.map((shape, idx) => <LearningCard key={idx} topElement={shape.shapeClass === 'triangle' ? <div className="w-0 h-0 border-l-[30px] border-l-transparent border-r-[30px] border-r-transparent border-b-[60px] border-b-indigo-500 mb-2"></div> : <div className={`w-16 h-16 bg-indigo-500 mb-2 ${shape.shapeClass}`}></div>} mainText={shape.ta} subText="" bottomText={shape.meaning} bottomSubText={shape.en} color="indigo" />)}</div>;
      case 'actions': return <div className="grid grid-cols-2 md:grid-cols-4 gap-6">{actionsData.map((action, idx) => <LearningCard key={idx} mainText={action.ta} subText="" bottomText={action.meaning} bottomSubText={action.en} color="cyan" />)}</div>;
      case 'sentences': return <div className="space-y-8"><div className="bg-orange-50/80 dark:bg-orange-900/10 p-6 rounded-3xl border border-orange-100 dark:border-orange-900/30 mb-8"><h3 className="text-xl font-bold font-tamil text-orange-800 dark:text-orange-300 mb-2">வாக்கிய அமைப்பு (Sentence Structure)</h3><p className="text-[#5c4235] dark:text-stone-400 mb-4">English uses <strong>SVO</strong> (Subject-Verb-Object). <br/>Tamil uses <strong>SOV</strong> (Subject-Object-Verb).</p></div><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{sentenceStructure.map((item, idx) => <div key={idx} className="bg-white/80 dark:bg-[#1a1a1a] rounded-3xl p-6 border border-[#eaddcf] dark:border-neutral-800 shadow-lg hover:-translate-y-1 transition-transform"><div className="mb-4 space-y-2"><div className="flex justify-between border-b border-[#eaddcf]/50 dark:border-neutral-800 pb-2"><span className="text-[#8a7060] text-xs font-bold uppercase">Subject</span><div className="text-right"><span className="block font-tamil font-bold text-[#3e2b22] dark:text-stone-200">{item.subject}</span><span className="text-xs text-stone-500">{item.subEn}</span></div></div><div className="flex justify-between border-b border-[#eaddcf]/50 dark:border-neutral-800 pb-2"><span className="text-[#8a7060] text-xs font-bold uppercase">Object</span><div className="text-right"><span className="block font-tamil font-bold text-[#3e2b22] dark:text-stone-200">{item.object}</span><span className="text-xs text-stone-500">{item.objEn}</span></div></div><div className="flex justify-between border-b border-[#eaddcf]/50 dark:border-neutral-800 pb-2"><span className="text-[#8a7060] text-xs font-bold uppercase">Verb</span><div className="text-right"><span className="block font-tamil font-bold text-[#3e2b22] dark:text-stone-200">{item.verb}</span><span className="text-xs text-stone-500">{item.verbEn}</span></div></div></div><div className="mt-4 pt-4 bg-orange-50/50 dark:bg-orange-900/20 -mx-6 -mb-6 p-6 rounded-b-3xl"><p className="font-tamil font-black text-xl text-orange-800 dark:text-orange-400 mb-1">{item.sentence}</p><p className="text-sm font-medium text-orange-600/70 dark:text-orange-400/70 italic">{item.meaning}</p></div></div>)}</div></div>;
      case 'phrases': return <div className="space-y-8">{commonPhrases.map((group, idx) => <div key={idx}><h3 className="text-2xl font-black font-tamil text-[#3e2b22] dark:text-white mb-6 pl-4 border-l-4 border-cyan-500">{group.category}</h3><div className="grid gap-4 md:grid-cols-2">{group.items.map((phrase, pIdx) => <div key={pIdx} className="bg-white/80 dark:bg-[#1a1a1a] p-6 rounded-2xl border border-[#eaddcf] dark:border-neutral-800 shadow-sm hover:border-cyan-200 transition-colors flex justify-between items-center group"><div><p className="font-tamil font-bold text-xl text-[#3e2b22] dark:text-stone-200 mb-1 group-hover:text-cyan-600">{phrase.ta}</p><p className="text-xs text-stone-400 font-bold uppercase tracking-wider">{phrase.en}</p></div><div className="text-right pl-4"><span className="text-sm font-medium text-cyan-800 dark:text-cyan-400 bg-cyan-50 dark:bg-cyan-900/20 px-3 py-1 rounded-lg">{phrase.meaning}</span></div></div>)}</div></div>)}</div>;
      case 'script': return <div className="space-y-8"><div className="bg-indigo-50/80 dark:bg-indigo-900/10 p-6 rounded-3xl border border-indigo-100 dark:border-indigo-900/30 mb-8 text-center"><p className="text-indigo-800 dark:text-indigo-300 font-medium">Tamil letters are easier to learn when grouped by shape. Practice writing these similar looking letters together.</p></div><div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">{scriptGroups.map((group, idx) => <div key={idx} className="bg-white/80 dark:bg-[#1a1a1a] rounded-[2rem] p-8 border border-[#eaddcf] dark:border-neutral-800 shadow-xl relative overflow-hidden"><div className="absolute top-0 right-0 p-4 opacity-10"><Icon name="pen" /></div><h4 className="text-sm font-bold uppercase tracking-widest text-stone-400 mb-6 border-b border-[#eaddcf]/50 pb-2">{group.name}</h4><div className="grid grid-cols-2 gap-4">{group.letters.map((char, cIdx) => <LearningCard key={cIdx} mainText={char} subText="" color="indigo" />)}</div></div>)}</div></div>;
      default: return null;
    }
  };

  return (
    <div className="max-w-7xl mx-auto pb-20 animate-fade-in">
      <SEO title={`${t('learnTamil', language)} | தமிழ்ச் சங்கம்`} description="Learn Tamil language basics, vowels, consonants, numbers, and vocabulary." />
      <Breadcrumbs items={breadcrumbs} />
      {activeSection ? (
        <div className="animate-fade-in">
           <div className="text-center mb-10"><h2 className="text-4xl md:text-5xl font-black font-tamil text-[#3e2b22] dark:text-white mb-4">{getSectionTitle(activeSection)}</h2>{(() => { const topic = topics.find(t => t.id === activeSection); if (topic?.descKey) return <p className="text-[#8a7060] dark:text-stone-400 text-lg max-w-2xl mx-auto leading-relaxed">{t(topic.descKey as any, language)}</p>; return null; })()}</div>
           {renderSectionContent()}
        </div>
      ) : renderDashboard()}
    </div>
  );
};

const LearningCard: React.FC<any> = ({ mainText, subText, bottomText, bottomSubText, topElement, color }) => {
    const colors: any = { rose: { text: 'text-rose-600 dark:text-rose-500', borderHover: 'hover:border-rose-200 dark:hover:border-rose-900', bgDeco: 'bg-rose-50 dark:bg-rose-900/20' }, blue: { text: 'text-blue-600 dark:text-blue-500', borderHover: 'hover:border-blue-200 dark:hover:border-blue-900', bgDeco: 'bg-blue-50 dark:bg-blue-900/20' }, purple: { text: 'text-purple-600 dark:text-purple-500', borderHover: 'hover:border-purple-200 dark:hover:border-purple-900', bgDeco: 'bg-purple-50 dark:bg-purple-900/20' }, amber: { text: 'text-amber-600 dark:text-amber-500', borderHover: 'hover:border-amber-200 dark:hover:border-amber-900', bgDeco: 'bg-amber-50 dark:bg-amber-900/20' }, teal: { text: 'text-teal-600 dark:text-teal-500', borderHover: 'hover:border-teal-200 dark:hover:border-teal-900', bgDeco: 'bg-teal-50 dark:bg-teal-900/20' }, emerald: { text: 'text-emerald-600 dark:text-emerald-500', borderHover: 'hover:border-emerald-200 dark:hover:border-emerald-900', bgDeco: 'bg-emerald-50 dark:bg-emerald-900/20' }, indigo: { text: 'text-indigo-600 dark:text-indigo-500', borderHover: 'hover:border-indigo-200 dark:hover:border-indigo-900', bgDeco: 'bg-indigo-50 dark:bg-indigo-900/20' }, orange: { text: 'text-orange-600 dark:text-orange-500', borderHover: 'hover:border-orange-200 dark:hover:border-orange-900', bgDeco: 'bg-orange-50 dark:bg-orange-900/20' }, cyan: { text: 'text-cyan-600 dark:text-cyan-500', borderHover: 'hover:border-cyan-200 dark:hover:border-cyan-900', bgDeco: 'bg-cyan-50 dark:bg-cyan-900/20' }, lime: { text: 'text-lime-600 dark:text-lime-500', borderHover: 'hover:border-lime-200 dark:hover:border-lime-900', bgDeco: 'bg-lime-50 dark:bg-lime-900/20' }, fuchsia: { text: 'text-fuchsia-600 dark:text-fuchsia-500', borderHover: 'hover:border-fuchsia-200 dark:hover:border-fuchsia-900', bgDeco: 'bg-fuchsia-50 dark:bg-fuchsia-900/20' }, sky: { text: 'text-sky-600 dark:text-sky-500', borderHover: 'hover:border-sky-200 dark:hover:border-sky-900', bgDeco: 'bg-sky-50 dark:bg-sky-900/20' } };
    const currentColors = colors[color];
    return (
        <div className={`group bg-white/80 dark:bg-[#1a1a1a] rounded-3xl p-6 border border-[#eaddcf] dark:border-neutral-800 shadow-sm hover:shadow-xl hover:-translate-y-2 ${currentColors.borderHover} transition-all duration-300 flex flex-col items-center text-center relative overflow-hidden h-full min-h-[220px] justify-between`}>
            <div className={`absolute -top-10 -right-10 w-32 h-32 ${currentColors.bgDeco} rounded-full transition-transform duration-500 group-hover:scale-150 opacity-60`}></div>
            {topElement && <div className="relative z-10 w-full flex justify-center mb-2">{topElement}</div>}
            <div className="relative z-10 flex-grow flex flex-col justify-center">
                    <span className={`text-4xl sm:text-5xl font-black font-tamil text-[#3e2b22] dark:text-stone-100 group-hover:${currentColors.text.split(' ')[0]} transition-colors leading-tight mb-1`}>{mainText}</span>
                    {subText && <div className="text-sm font-bold text-stone-400 uppercase tracking-wider">{subText}</div>}
            </div>
            {(bottomText || bottomSubText) && (
                <div className="mt-4 w-full pt-4 border-t border-[#eaddcf]/50 dark:border-neutral-800 relative z-10">
                    {bottomText && <p className="font-tamil font-bold text-[#5c4235] dark:text-stone-300 text-lg leading-snug">{bottomText}</p>}
                    {bottomSubText && <p className="text-[10px] text-stone-400 font-bold uppercase mt-1">{bottomSubText}</p>}
                </div>
            )}
        </div>
    );
};
